### Google Homepage
GET https://www.google.com

### Homepage
GET http://localhost:8082
Content-Type: application/json

### MVC: update a technique's description
POST http://localhost:8082/technique/update
Content-Type: application/x-www-form-urlencoded
Accept: text/html

id=3&description=Powerkick

### Taekwondo Homepage
GET http://localhost:8082/taekwondo
Content-Type: application/json

### API: Retrieve all students
GET http://localhost:8082/api/students
Content-Type: application/json

### API: Retrieve one student by ID
GET http://localhost:8082/api/students/1
Content-Type: application/xml

### API: Retrieve one student by ID (not found)
GET http://localhost:8082/api/students/999
Content-Type: application/xml

### API: Retrieve all techniques of a specific student by ID
GET http://localhost:8082/api/students/1/techniques
Content-Type: application/xml

### API: Search students
GET http://localhost:8082/api/students?searchTerm=J
Content-Type: application/json

### API: Delete a student by ID

# @no-redirect
DELETE http://localhost:8082/api/students/1
Cookie: JSESSIONID=6A84BED82B2445E1DEDF11A2799C6867
X-Csrf-Token: A15aNqdccpxQys6CPkSCUqKRP8yn2FKMG1_LOIcP0YvgIqUbOjpsBsVuFP59_PrjDGm2apqgEvXF6WChfWb4CbZq57jSG5Et

### API: Delete a student by ID (with no csrf token)
DELETE http://localhost:8082/api/students/1
Cookie: JSESSIONID=6A84BED82B2445E1DEDF11A2799C6867


### API: create an issue (bad request)

POST http://localhost:8082/api/students
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "startDate": "This is a bad date"
}

### API: create a student (good request)

POST http://localhost:8082/api/students
Accept: application/xml
Content-Type: application/json

{
  "name": "John Doe",
  "startDate": "2020-01-01"
}

### API: change a student's start date (no content)

PATCH http://localhost:8082/api/students/2
COOKIE: JSESSIONID=40F82C6FC0D27EF1EED8B3366C2989E
#X-Csrf-Token: bALi-G8DZyf0SAwVgUT3_GVWilVs_2I9e-8DXYFwCvpCOMCCVWbUyA0xAUXZfjh0s2nDxF1np2wOzlAQHdYwbLAVPMlwAfS0




{
  "startDate": "2020-01-01"
}

### API: change a student's start date (good request)

PATCH http://localhost:8082/api/students/2
Content-Type: application/json

{
  "startDate": "2020-01-01"
}

### API: change a student's start date (not found)

PATCH http://localhost:8082/api/students/999
COOKIE: JSESSIONID=6A84BED82B2445E1DEDF11A2799C6867
X-Csrf-Token: A15aNqdccpxQys6CPkSCUqKRP8yn2FKMG1_LOIcP0YvgIqUbOjpsBsVuFP59_PrjDGm2apqgEvXF6WChfWb4CbZq57jSG5Et

{
  "startDate": "The new start date"
}

### API: change a student's start date (bad request)

PATCH http://localhost:8082/api/students/1
Content-Type: application/json

{
  "startDate": ""
}