### Google Homepage
GET https://www.google.com

### Homepage
GET http://localhost:8081
Content-Type: application/json

### Taekwondo Homepage
GET http://localhost:8081/taekwondo
Content-Type: application/json

### API: Retrieve all students
GET http://localhost:8081/api/students
Content-Type: application/json

### API: Retrieve one student by ID
GET http://localhost:8081/api/students/1
Content-Type: application/json

### API: Retrieve all techniques of a specific student by ID
GET http://localhost:8081/api/students/1/techniques
Content-Type: application/json

### API: Search students
GET http://localhost:8081/api/students/search?query=search_term_here
Content-Type: application/json

### API: Delete a student by ID
DELETE http://localhost:8081/api/students/2
Content-Type: application/json
